#!/bin/bash

ispkg=1

URL="https://gerrit.automotivelinux.org/gerrit/gitweb?p=AGL/AGL-repo.git;a=blob_plain;f=${1:-default}.xml;hb=HEAD"

tmpout=$(mktemp /tmp/$(basename $0).XXXXXXXX)
trap "rm -f $tmpout" STOP INT QUIT EXIT ERR

echo "Using URL: $URL"
curl -s $URL >$tmpout 

$(dirname $0)/repo2manifest $tmpout
