#!/bin/bash

set -e

function error() {
	echo "ERROR: $@" >&2
	exit 1
}

. /etc/xdtrc

SCRIPTDIR=$(cd $(dirname $0) && pwd -P)

SERVER=apache@vm-www

MACHINE=${1:-m3ulcb}
SERVER_DIR=/download/public/2018/Flounder+/$MACHINE

echo "Publishing image for MACHINE $MACHINE to $SERVER:$SERVER_DIR"

IMGDIR=$XDT_BUILD/$MACHINE/tmp/deploy/images/$MACHINE
SDKDIR=$XDT_BUILD/$MACHINE/tmp/deploy/sdk/

# locate image
[[ ! -d $IMGDIR ]] && error "No images dir in $IMGDIR"
pushd $IMGDIR
lnkname=$(find . -type l -name "*.wic.xz")
[[ -z "$lnkname" ]] && lnkname=$(find . -type l -name "*.wic.vmdk") # exception for qemu
[[ ! -e $lnkname ]] && error "No image link found in $IMGDIR" || echo "Found image link $lnkname"
imgfile=$(readlink $lnkname)
[[ ! -f $imgfile ]] && error "No image found in $IMGDIR" || echo "Found image file $imgfile"

bmaplnkname=$(find . -type l -name "*.wic.bmap")
[[ -e $bmaplnkname ]] && bmapfile=$(readlink $bmaplnkname) && echo "Found bmap link $bmaplnkname, file $bmapfile"
popd

# locate SDK
[[ ! -d $SDKDIR ]] && error "No SDK dir in $SDKDIR"
pushd $SDKDIR
sdkfile=$(find . -type f -name "poky-*.sh")
[[ ! -f $sdkfile ]] && error "Unable to find SDK file in $SDKDIR"
popd

# determine version
[[ "$imgfile" =~ -([0-9]+)\.rootfs\.wic\..+$ ]] && VERSION=${BASH_REMATCH[1]} || error "Unable to find image version"

### push everything

# create remote
ssh $SERVER mkdir -p $SERVER_DIR/$VERSION/{sdk,images}

# send files
RSYNCPATH=$SERVER:$SERVER_DIR/$VERSION
rsync -Pav $IMGDIR/$imgfile $IMGDIR/*-$VERSION.rootfs.manifest $RSYNCPATH/images/
[[ -e $IMGDIR/$bmapfile ]] && rsync -Pav $IMGDIR/$bmapfile $RSYNCPATH/images/
rsync -Pav $SDKDIR/ $RSYNCPATH/sdk/
rsync -Pav $SCRIPTDIR/*.html $RSYNCPATH/

# handle firmware if any (Renesas M3/H3/...)
FWFILES=$(find $IMGDIR -type f -name "*.srec")
if [[ -n "$FWFILES" ]]; then
	ssh $SERVER mkdir -p $SERVER_DIR/$VERSION/firmware
	rsync -Pav $FWFILES $RSYNCPATH/firmware/
	cat <<EOF | ssh $SERVER "cat >$SERVER_DIR/$VERSION/firmware/README"
The files here can be used to flash the M3ULCB board firmware.

Full procedure is detailed here: https://elinux.org/R-Car/Boards/M3SK#Flashing_firmware
EOF
fi

# create links
CMD="ln -sfv $imgfile $SERVER_DIR/$VERSION/images/$lnkname"
[[ -n "$bmaplnkname" ]] && CMD="$CMD; ln -sfv $bmapfile $SERVER_DIR/$VERSION/images/$bmaplnkname"
CMD="$CMD; ln -sfv $sdkfile $SERVER_DIR/$VERSION/sdk/agl-sdk-latest.sh"
CMD="$CMD; ln -snfv $SERVER_DIR/$VERSION $SERVER_DIR/latest"
CMD="$CMD; rm -f $SERVER_DIR/latest_is_*"
CMD="$CMD; ln -snfv $SERVER_DIR/$VERSION $SERVER_DIR/latest_is_$VERSION"
CMD="$CMD; echo $VERSION >$SERVER_DIR/latest.txt"
CMD="$CMD; pushd $SERVER_DIR/$VERSION/images; md5sum * >files.md5; popd"

ssh $SERVER "$CMD"

echo "Image successfully pushed to: http://iot.bzh$SERVER_DIR/$VERSION"


