#!/bin/bash

. /etc/xdtrc

cd $(dirname $0)

# copy scripts/binaries
DEST=~/bin
mkdir -p $DEST
install --mode=755 -t $DEST bin/*

# copy conf without overwriting
DEST=$XDT_DIR
mkdir -p $DEST

pushd etc
	for x in *; do
		[[ ! -f $DEST/$x ]] && cp -v $x $DEST/$x
	done
popd


