#!/bin/bash

set -e

function error() {
	echo "ERROR: $@" >&2
	exit 1
}

. /etc/xdtrc

SCRIPTDIR=$(cd $(dirname $0) && pwd -P)

SERVER=apache@vm-www
SERVER_DIR=/download/public/2018/Chromium

MACHINE=m3ulcb

PACKAGES="aarch64/chromium-ozone-wayland noarch/hicolor-icon-theme"

IMGDIR=$XDT_BUILD/$MACHINE/tmp/deploy/images/$MACHINE
SDKDIR=$XDT_BUILD/$MACHINE/tmp/deploy/sdk/
RPMDIR=$XDT_BUILD/$MACHINE/tmp/deploy/rpm/

# locate image
[[ ! -d $IMGDIR ]] && error "No images dir in $IMGDIR"
pushd $IMGDIR
lnkname=$(find . -type l -name "*.wic.xz")
[[ ! -e $lnkname ]] && error "No image link found in $IMGDIR" || echo "Found image link $lnkname"
imgfile=$(readlink $lnkname)
[[ ! -f $imgfile ]] && error "No image found in $IMGDIR" || echo "Found image file $imgfile"

bmaplnkname=$(find . -type l -name "*.wic.bmap")
[[ -e $bmaplnkname ]] && bmapfile=$(readlink $bmaplnkname) && echo "Found bmap link $bmaplnkname, file $bmapfile"
popd

# locate SDK
[[ ! -d $SDKDIR ]] && error "No SDK dir in $SDKDIR"
pushd $SDKDIR
sdkfile=$(find . -type f -name "poky-*.sh")
[[ ! -f $sdkfile ]] && error "Unable to find SDK file in $SDKDIR"
popd

# rpms
[[ ! -d $RPMDIR ]] && error "No RPM dir in $RPMDIR"

# determine version
[[ "$imgfile" =~ -([0-9]+).rootfs.wic.xz$ ]] && VERSION=${BASH_REMATCH[1]} || error "Unable to find image version"

### push everything

# create remote
ssh $SERVER mkdir -p $SERVER_DIR/$VERSION/{sdk,images,firmware}

# send files
RSYNCPATH=$SERVER:$SERVER_DIR/$VERSION
rsync -Pav $IMGDIR/$imgfile $RSYNCPATH/images/
rsync -Pav $(find $IMGDIR -type f -name "*.srec") $RSYNCPATH/firmware/
[[ -e $IMGDIR/$bmapfile ]] && rsync -Pav $IMGDIR/$bmapfile $RSYNCPATH/images/
rsync -Pav $SDKDIR/ $RSYNCPATH/sdk/
rsync -Pav $SCRIPTDIR/*.html $RSYNCPATH/

pushd $RPMDIR
	for pkg in $PACKAGES; do
		ARCH=$(dirname $pkg)
		ssh $SERVER mkdir -p $SERVER_DIR/$VERSION/packages/$ARCH
		rsync -Pav --exclude "*-dbg-*" --exclude "*-dev-*" $pkg-*.rpm $RSYNCPATH/packages/$ARCH/
	done
popd


cat <<EOF | ssh $SERVER "cat >$SERVER_DIR/$VERSION/firmware/README"
The files here can be used to flash the M3ULCB board firmware.

Full procedure is detailed here: https://elinux.org/R-Car/Boards/M3SK#Flashing_firmware
EOF

# create links
CMD="ln -sfv $imgfile $SERVER_DIR/$VERSION/images/$lnkname"
[[ -n "$bmaplnkname" ]] && CMD="$CMD; ln -sfv $bmapfile $SERVER_DIR/$VERSION/images/$bmaplnkname"
CMD="$CMD; ln -sfv $sdkfile $SERVER_DIR/$VERSION/sdk/agl-sdk-latest.sh"
CMD="$CMD; ln -snfv $SERVER_DIR/$VERSION $SERVER_DIR/latest"
CMD="$CMD; rm -f $SERVER_DIR/latest_is_*"
CMD="$CMD; ln -snfv $SERVER_DIR/$VERSION $SERVER_DIR/latest_is_$VERSION"
CMD="$CMD; echo $VERSION >$SERVER_DIR/latest.txt"
CMD="$CMD; pushd $SERVER_DIR/$VERSION/images; md5sum * >files.md5; popd"

ssh $SERVER "$CMD"

echo "Image successfully pushed to: http://iot.bzh$SERVER_DIR/$VERSION"


