#!/bin/bash

TOPDIR=$(realpath $(dirname $(realpath $BASH_SOURCE))/..)

. $TOPDIR/bin/libzh.sh

DEPTEST=$XDT_DIR/deploy_test
mkdir -p $DEPTEST

# simulate folders as created by save_deploy

# TODO




